g fpt improvements

diff --git a/bin/git-force-push-this b/bin/git-force-push-this
--- a/bin/git-force-push-this
+++ b/bin/git-force-push-this
@@ -11,13 +11,21 @@ if [ "$LOCAL_BRANCH" = "master" ]; then
   (>&2 echo "For safety, you cannot use this to force push master.")
   exit 2
 fi
+if [ "$LOCAL_BRANCH" = "main" ]; then
+  (>&2 echo "For safety, you cannot use this to force push main.")
+  exit 2
+fi
 
 REMOTE_BRANCH="`echo $REMOTE_REF | cut -d/ -f2-`"
 if [ "$REMOTE_BRANCH" = "master" ]; then
   (>&2 echo "For safety, you cannot use this to force push to master.")
   exit 3
 fi
+if [ "$REMOTE_BRANCH" = "main" ]; then
+  (>&2 echo "For safety, you cannot use this to force push to main.")
+  exit 3
+fi
 
 REMOTE_REPO="`echo $REMOTE_REF | cut -d/ -f1`"
 
-git push -f "$REMOTE_REPO" "$REMOTE_BRANCH"
+git push --force-with-lease --force-if-includes "$REMOTE_REPO" "$REMOTE_BRANCH"
